DROP TABLE IF EXISTS Reality_Kopicova.Users;
CREATE TABLE Users(
    Id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UserName VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(500) NOT NULL,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Reality_Kopicova.Realestates;
CREATE TABLE Realestates(
    Id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nadpis VARCHAR(1000) NOT NULL,
    Cena INTEGER NOT NULL,
    Lokalita VARCHAR(200) NOT NULL,
    TypNemovitosti VARCHAR(100) NOT NULL,
    Plocha INTEGER NOT NULL,
    Popis VARCHAR(5000) NOT NULL,
    DateAdded DATETIME NOT NULL,
    UserId INTEGER NOT NULL,
    FOREIGN KEY(UserId) REFERENCES Reality_Kopicova.Users(Id)
);

